FROM fedora:24
# Thermostat Agent Image.
#
# Volumes:
#  * /opt/rh/rh-thermostat16/root/usr/share/thermostat
# Environment:
#  * $THERMOSTAT_CMDC_PORT      - The command channel listen port.
#  * $THERMOSTAT_CMDC_ADDR      - The command channel listen address.
#  * $THERMOSTAT_AGENT_USERNAME - User name for the thermostat agent to use
#                                 for connecting to storage.
#  * $THERMOSTAT_AGENT_PASSWORD - Password for the thermostat agent to use
#                                 for connecting to storage.
#  * $THERMOSTAT_DB_URL         - The storage URL to connect to.

LABEL Name="thermostat-19-agent-docker" \
      Version="1.99" \ 
      Release="1.0" \
      Architecture="x86_64"

RUN dnf install -y mercurial maven mongodb mongodb-server java-1.8.0-openjdk-devel libsecret-devel make gcc gtk2-devel autoconf automake libtool procps-ng passwd --setopt=deltarpm=0 && dnf clean all

RUN dnf update -y --setopt=deltarpm=0 && dnf clean all

ENV THERMOSTAT_VERSION=1.99
ENV HOME=/root
ENV USER=root

ENV THERMOSTAT_CMDC_ADDR 127.0.0.1
ENV THERMOSTAT_CMDC_PORT 12000
ENV THERMOSTAT_DB_URL http://127.0.0.1:8999/thermostat/storage
ENV THERMOSTAT_HOME /root/thermostat/distribution/target/image
ENV USER_THERMOSTAT_HOME /root/.thermostat

EXPOSE $THERMOSTAT_CMDC_PORT

COPY __tms__ /root/thermostat
RUN cd /root/thermostat && mvn -Dmaven.test.skip=true clean integration-test

COPY thermostat-user-home-config ${USER_THERMOSTAT_HOME}
ADD root /

# For the agent vm-profiler to work thermostat jars need to be available to other containers
# using the volumes from this container.
VOLUME ${THERMOSTAT_HOME}

WORKDIR ${THERMOSTAT_HOME}

ENTRYPOINT ["container-entrypoint"]
CMD [ "run-thermostat-agent" ]
